### ISSUE TITLE
Firegestures broken in Firefox Nightly

### ISSUE THREAD

**Issue by mpopp75** [gomita/firegestures#109]
No mouse gestures work in Firefox Nightly currently. I first noticed it with the Nightly of November 25.

Using Firefox 45.0 on Linux64, Firegestures 1.10.3.

**Comment by jasontibbitts** [comment]
Seeing the same thing here.  The gesture trails are still shown, but there is no small popup at the bottom showing what has been drawn, and in the preferences dialog the mapping pane is completely empty.

**Comment by ryanbr** [comment]
I can also confirm this.

**Comment by Fanolian** [comment]
It's bug 1226869, and all the related bugs from bug 1228116.

**Comment by jasontibbitts** [comment]
Appears to be working fine with a more recent nightly.

**Comment by mpopp75** [comment]
I see it still broken with the Nightly of November 30.

**Comment by gomita** [comment]
I can reproduce it on the latest Nightly.

Error: undefined entity
Source File: chrome://firegestures/content/browser.rdf
Line: 117, Column: 3
Source Code:
  <RDF:Description RDF:about="urn:category:navigation"

**Comment by Quaturn** [comment]
I have the same problem.

**Comment by Fanolian** [comment]
It is fixed in Nightly 2015-12-04 build.

**Comment by gomita** [comment]
I can confirm the bug has been fixed on the latest Nightly 45.0a1 (2015-12-04)
@Fanolian thanks!
