### ISSUE TITLE
Tab Groups gesture is not working with Tab Groups extension enabled

### ISSUE THREAD

**Issue by vkapovit** [gomita/firegestures#115]
Tab Groups gesture does not work with the Tab Groups Extension enabled in FF44. Since built in Tab Groups will disappear in FF45 could you change the implementation of the Tab Groups gesture for FF45 and later please?
As suggested by the author of the Tab Groups extension one can currently get around this issue by mapping a gesture to the following script
   TabView.toggle();

**Comment by gomita** [comment]
Thanks.
I fixed it to add work-around Tab Groups command by the way to show a dialog to prompt user to add script.
commit: 57a0b360377f96623e0bc27bef97fcfb09e760ba
