### ISSUE TITLE
Scroll to Top/Bottom fails since Nightly 2016-01-27 due to bug 1233497

### ISSUE THREAD

**Issue by Fanolian** [gomita/firegestures#116]
This is possibly due to [Bug 1233497 - Make unsafe CPOWs from non-addon browser code throw by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1233497). (More info [here](https://groups.google.com/d/msg/mozilla.dev.platform/Nstdr9vsSWI/c7E2lhLoAwAJ))

Steps to reproduce:
0. Install FireGestures 1.10.3
1. Assign gestures to Scroll to Top/Bottom.
2. Draw the gestures

Actual result:
The gestures fail. Error is `Gesture failed: (Error: Unsafe CPOW usage forbidden)`. A similar warning appears in browser console as well.
I don't use many gestures so there are perhaps more functions are blocked by the issue.

P.S. 
Workaround: toggling `dom.ipc.cpows.forbid-unsafe-from-browser` fixes the issue.

Crossposted to Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1243625

**Comment by gomita** [comment]
I cannot reproduce this bug on the latest Nightly 47.0a1 (2016-01-30).
Can you confirm that the gesture is actually assigned to "Scroll to Top/Bottom"?
"Scroll to Top/Bottom" should not use CPOW.

**Comment by Fanolian** [comment]
I didn't test it thoroughly. Sorry about that.

The issue requires the combination of 3 extensions:
1. Firegesture 1.10.4: https://addons.mozilla.org/en-US/firefox/addon/firegestures/versions/
2. Tab Mix Plus Version 0.4.2.1pre.160124a1: https://addons.mozilla.org/en-US/firefox/addon/tab-mix-plus/versions/
3. Tree Style Tab 0.16.2015122501: https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/versions/
(Or Tree Style Tab nightly: https://piro.sakura.ne.jp/xul/xpi/nightly/ ; Require xpinstall.signatures.required;false)

Install all 3 in a new profile, keep all in default settings, and I can reproduce the issue.
Disabling either TMP or TST does not trigger the unsafe CPOW usage forbidden warning.

I think the culprit may lie on the interaction between Tab Mix Plus and Tree Style Tab, but FireGestures somehow exposes the bug.

I'll try to do more testing but I don't think I will get more useful information.

**Comment by Fanolian** [comment]
The issue is fixed by the latest nightly build of Tree Style Tab (0.17.2016031800a192017). More info here: https://github.com/piroor/treestyletab/issues/1093
