### ISSUE TITLE
Open in 'new tab'/'hybrid save as' don't work on Nightly, "unsafe CPOW usage" (since mozilla bug 1233497)

### ISSUE THREAD

**Issue by mayhemer** [gomita/firegestures#117]
Regression from https://bugzilla.mozilla.org/show_bug.cgi?id=1233497

STR:
- fresh profile
- install FireGestures
- do an "UP" gesture on any (http preferably) link on any page
- a new tab opens

Expected:
- the url starts loading

Actual:
- page is not loading, only the URL is filled in the address bar (only pressing enter when address bar is focused makes the page loading)

Similar for "hybrid save as" (=DL gesture).  Nothing happens, browser console "unsafe CPOW usage" warnings appear.

See mozilla bug at https://bugzilla.mozilla.org/show_bug.cgi?id=1244089 for more details (cross-post)

**Comment by gomita** [comment]
Fixed: commit 94bd8536fdf6f9e2c5ff2f43953458da4f65be7e

**Comment by mayhemer** [comment]
Thanks!  I will wait for this propagate to AMO.
