### ISSUE TITLE
All gestures lost after upgrading to FF 45 ESR

### ISSUE THREAD

**Issue by emelsk** [gomita/firegestures#122]
I just upgraded from 38.7 ESR to 45 ESR and all gestures are gone. I can't even assign any gesture to the Mapping tab in Options as Name/Command/Gesture list is completely empty. Re-install of the add-on didn't help.

**Comment by lucasvel** [comment]
Same here.
Name: Firefox
Version: 45.0
Build ID: 20160304114926
User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
Multiprocess Windows: 0/1 (default: false)
Safe Mode: false

**Comment by ChristophScherrer** [comment]
dito over here in FF 45.01
A Mouse Gesture shows the message: Unknown Gesture: L  (move left)
In Mapping - View Source: I can see all gestures 
But in **Mapping - Browser: the TABLE is EMPTY**
tried to find the firegestures.sqlite definition file - but could not find it in any browser directory

**Comment by lucasvel** [comment]
By looking at the latest reviews for the extension in the Firefox add-ons page it seems working for some people.
My best guess is that something broke during the upgrade to FF45. 
I have too many things in my current profile and creating a new one it's not an option for me right now.
I can help with whatever information may be needed to help debug this issue, I really miss the firegestures behaviour.

**Comment by ChristophScherrer** [comment]
Same with me - let me know what additional infos are required to trace this issue...
As mentioned by emelsk - reinstalling the add-on does NOT help - still same issue. Here again: if you tell us how to REALLY delete the add-on, so that a new add will do the job - would help.

**Comment by Chisnet** [comment]
Also seeing this issue, upgraded from Firefox 44 to 45 on Mac and experiencing the same complete lack of preferences. Removing and re-installnig actually made the problem kind of worse, before removing I could see some options in the gesture list, but they were unbound and I couldn't edit them. After re-installing the list is completely empty of any gestures.

**Comment by Chisnet** [comment]
Still seeing this issue, really tricky getting use to gesture free navigation :-(

**Comment by emelsk** [comment]
I spent some time trying to come up with at least a workaround, but the fix is beyond my knowledge/skills. Maybe someone/developer could use the following clues to figure out what's going on here:

* Browser Console errors:

* `undefined entity in browser.rdf:117:3 [[chrome://firegestures/content/browser.rdf]]`
* `TypeError: res is null in xdGestureMapping.js:122:9 [[jar:file:///path-to-firefox-profile/extensions/firegestures@xuldev.org.xpi!/components/xdGestureMapping.js]]`
* `NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "res is null" {file: "jar:file:///path-to-firefox-profile/extensions/firegestures@xuldev.org.xpi!/components/xdGestureMapping.js" line: 122}]'[JavaScript Error: "res is null" {file: "jar:file:///path-to-firefox-profile/extensions/firegestures@xuldev.org.xpi!/components/xdGestureMapping.js" line: 122}]' when calling method: [xdIGestureMapping::init] in xdGestureService.js:69:0 [[jar:file:///path-to-firefox-profile/extensions/firegestures@xuldev.org.xpi!/components/xdGestureService.js]]`
* `TypeError: this._gestureMapping is null
FireGestures.onDirectionChanged() browser.js:101 [[chrome://firegestures/content/browser.js]]
FGH__progressGesture() xdGestureHandler.js:415 [[jar:file:///path-to-firefox-profile/extensions/firegestures@xuldev.org.xpi!/components/xdGestureHandler.js]]
FGH_handleEvent() xdGestureHandler.js:215 [[jar:file:///path-to-firefox-profile/extensions/firegestures@xuldev.org.xpi!/components/xdGestureHandler.js]]
 in browser.js:101:8 [[chrome://firegestures/content/browser.js]]`

where path-to-firefox-profile is Profile Folder value from [[about:support]].

(Editing comment: I tried to use markdown to make this comment less painful for eyes, but links were not 'accepted' - therefore I enclosed them in double brackets [[ and ]] respectively since some of the errors contain brackets themselves.)

* Upon reinstall (or the initial install) of the add-on, Mapping list is not as empty as it appears. The definitions from chrome/content/firegestures/browser.rdf are pulled in, however corrupt. Gestures have no descriptions nor assigned directions (term used from browser.rdf) - think of it as of a table containing blank cells (rows/columns). These can in fact be edited and directions assigned and the gestures will work during current browser session. They are even stored in firegestures.sqlite file in path-to-firefox-profile folder - I verified that via sqlite3 tools:

`sqlite> .open firegestures.sqlite`
`sqlite> .tables`
`gesture_mappings`
`sqlite> select * from gesture_mappings;`
`0||category:navigation|`
`0||Browser:Back|L`
`0||Browser:Forward|R`
`0||Browser:Reload|UD`
`0||Browser:ReloadSkipCache|UDU`
`...`

Upon browser restart, things go south though: firegestures.sqlite still keeps its contents, but the UI never reads it in correctly and this time, there are no blank-like rows; Mapping list really is empty and gestures don't work anymore. Looks like the whole firegestures service doesn't start properly with the following error in the console:

`NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "res is null" {file: "jar:file:///path-to-firefox-profile/extensions/firegestures@xuldev.org.xpi!/components/xdGestureMapping.js" line: 122}]'[JavaScript Error: "res is null" {file: "jar:file:///path-to-firefox-profile/extensions/firegestures@xuldev.org.xpi!/components/xdGestureMapping.js" line: 122}]' when calling method: [xdIGestureMapping::init] in xdGestureService.js:69:0 [[jar:file:///path-to-firefox-profile/extensions/firegestures@xuldev.org.xpi!/components/xdGestureService.js]]`

**Comment by lucasvel** [comment]
FYI I just had an issue with another extension that was updated and wasn't working and by disabling my other addons I found out that by disabling "BM 2.2.4 CCK - Customizations to enhance the browsing experience inside the IBM intranet" FireGestures works again

**Comment by emelsk** [comment]
That's an interesting development. FWIW for the others, the 'another extension' is [Tab Groups](https://github.com/Quicksaver/Tab-Groups/issues/239).

**Comment by emelsk** [comment]
CCK turns out to be a real culprit here - see https://github.com/mkaply/cck2wizard/issues/14 for more details. There's an option of dirty hack to get things back to normal immediately, provided you're running ESR or DE editions of Firefox (and willing to accept unsigned add-ons), but I'd recommend to talk to your IT to have your company's CCK re-spinned using the updated CCK Wizard once it's xpi becomes available (I've seen the fix in github only so far).
