### ISSUE TITLE
[e10s] '[pooup] Back / Forward History' error

### ISSUE THREAD

**Issue by happysurf** [gomita/firegestures#124]
In all Firefox Aurora and Nightly with e10s this wheel mouse gesture doesn't work also with your last 1.10.6 version.
Options > Wheel Gestures > Scroll up with holding right button: [pooup] Back / Forward History, I get an error.
Please fix.
Thanks.

**Comment by gomita** [comment]
Error: [Exception... "Method not implemented'Method not implemented' when calling method: [nsIWebNavigation::sessionHistory]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame :: chrome://firegestures/content/browser.js :: FireGestures._buildPopup :: line 1012"  data: no]

**Comment by happysurf** [comment]
Yes, exactly.
In addition on a similar gesture > "Wheel Gestures > Scroll down with holding right-button > [Popup] List All Tabs", together the popup, the page have a small scroll down movement.
With e10s disabled this bejavour is not present.

**Comment by gomita** [comment]
Fixed.
commit:f8e1f421cf24f2fdb919beaba145304d315196d4
