### ISSUE TITLE
Closing a tab prompting for confirmation will ignore the "Stay on Page" choice

### ISSUE THREAD

**Issue by mleyen** [gomita/firegestures#125]
When closing a page with the associated gesture, if the page needs confirmation (onbeforeunload), the dialog will appear, but the tab will close regardless of choice. Clicking on "Stay on Page" does not prevent the tab from being closed.

This only happens when using the gesture. Regular closing (from the tab bar or Ctrl-W) uses the standard behavior.
You can test it here: http://www.4guysfromrolla.com/demos/OnBeforeUnloadDemo1.htm

Is this intended? Would it be possible to fix it so "Stay on Page" actually stops the tab from closing?

**Comment by gomita** [comment]
Confirmed.
