### ISSUE TITLE
Tab wheel gesture broken with last firefox versions 47 and 48

### ISSUE THREAD

**Issue by jreybert** [gomita/firegestures#127]
I am using firefox developer edition.

I can't switch tabs with the mouse wheel with:

- the very last 47 update (2016-04-28)
- the new 48 update (2016-04-29)

**Comment by mstange** [comment]
Apparently this was caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1263975 . Please let me know if I can help.

**Comment by avih** [comment]
I think it started on Nightly (47) on 2016-04-19. Here: https://bugzilla.mozilla.org/show_bug.cgi?id=1263975

I posted a comment there that addons were affected.

**Comment by PRiMENON** [comment]
+1

**Comment by gomita** [comment]
Fixed.
97ad80fc9a321935d7cd00e9ba87d66bf1eaabf5

**Comment by mstange** [comment]
Thanks!
