### ISSUE TITLE
"Save Image Now" feature doesn't work as intended in Firefox 45 ESR

### ISSUE THREAD

**Issue by reallyuniquename** [gomita/firegestures#141]
Firefox 45.3 ESR, FireGestures 1.10.9-1.10.12.

"Save Image Now" feature doesn't work as intended in Firefox 45 ESR, it opens "Save As" dialog.

**Comment by reallyuniquename** [comment]
I've updated to 1.10.13, it still opens up a 'save as' dialog.

**Comment by gomita** [comment]
In Firefox menubar, Tools > Options > General > Downloads > Save files to, you should decide the destination folder.

**Comment by reallyuniquename** [comment]
It is set to "Always ask me where to save files" and I need this option to stay exactly like this.

**Comment by reallyuniquename** [comment]
Is it possible to have "save image now" feature AND have "Always ask me where to save files" enabled in options?

**Comment by reallyuniquename** [comment]
Any updates?

**Comment by gomita** [comment]
> Is it possible to have "save image now" feature AND have "Always ask me where to save files" enabled in options?

No. FireGestures uses the folder path which is set as the Firefox option.

**Comment by reallyuniquename** [comment]
But my download folder path is set in options.
