### ISSUE TITLE
Incompatibility between the FireGestures and latest Lastpass extensions

### ISSUE THREAD

**Issue by evmcl** [gomita/firegestures#160]
There is an incompatibility between the FireGestures and latest Lastpass extensions on Firefox that will cause the browser to crash when the rocker gestures are used to navigate forward or back in history.

To reproduce:

1. Start a new instance of firefox and create a fresh, blank profile. (firefox --new-instance -ProfileManager)

2. Install the FireGestures extension. (Open Add-ons Manager and search) Re-start firefox.

3. a) Open preferences for FireGestures.
   b) Select "Advanced" tab.
   c) Enable "Rocker Gestures"
   d) Select "Back" for "Left-click with holding right-button.
   e) Close.

3. Go to https://www.lastpass.com/ and click the red "Get LastPass Free" button to install the extension. Follow prompts to allow and install. Re-start firefox.

4. Go to http://api.jquery.com/

5. Enter "post" into the search box and press enter.

6. Click the entry for jQuery.post()

7. Hold down the right mouse button and click the left mouse button.

Browser will crash.

Versions:
FireGestures 1.11
LastPass 4.1.45.3a

**Comment by evmcl** [comment]
See also: https://forums.lastpass.com/viewtopic.php?f=14&t=252605

**Comment by WhiteZeroX** [comment]
Thanks for reporting this! I've been having tons of crashes lately and have the same add-on setup.

**Comment by evmcl** [comment]
As appears that the issue was fixed on the LastPass side with release [4.1.46](https://lastpass.com/upgrade.php?fromwebsite=1&releasenotes=1) of their addon.

I've been running 4.1.49 with rocker gestures enabled for a while now with no problems.
