### ISSUE TITLE
[Request] Disable firegestures on specific domains

### ISSUE THREAD

**Issue by fvdnabee** [gomita/firegestures#29]
Hi,

When using the Gmail webclient it would be useful to disable the Firegestures add-on to let the Gmail Labs Gestures function take over. The Google Labs gestures are specifically tuned to meet the webclient needs, whereas the firegestures'  gestures are not.
In general a nifty feature would be to the ability to disable Firegestures on domains that can be specified via user-input, e.g. "*.mail.google.com".

Kinds regards,
fvdnabee

**Comment by HairyFotr** [comment]
+1

**Comment by Melog01** [comment]
+1

**Comment by gomita** [comment]
Try the new beta version:
https://addons.mozilla.org/firefox/addon/firegestures/versions/?page=1#version-1.11b1

To disable gestures on specific domains:
In 'about:config', search 'extensions.firegestures.blocked_hosts', set the value like '*.example.com, .google.com, www.yahoo.com'.

**Comment by Melog01** [comment]
After installation of b1 and also b3 I have in config only mousetrail.color valkue. All other values which are visible after installation 1.10.13 (and also reinstallation after b1) are missing

**Comment by gomita** [comment]
Sorry.
The version 1.11b3 is corrupt.
Please update to version 1.11b4.
