### ISSUE TITLE
Firegestures disable gmail inbox refresh

### ISSUE THREAD

**Issue by 8la** [gomita/firegestures#95]
Hi, 

When i have firegestures enabled my inbox on my googleapps company web email inbox doesn refresh automatically. I have to press the refresh button. 

Tested multiple times enabling and disabling the extension. Even uninstalled an reinstalled again, and inbox refresh still failing..

Versions:
 - Firefox 35
 - Ubuntu 14.04
 - FireGestures 1.8.7

**Comment by gomita** [comment]
I cannot reproduce it.

**Comment by 8la** [comment]
Yea, other firefox profile, does not have the bug... cant see the cause... closing for now.
