### ISSUE TITLE
Use html5 canvas to draw tracks instead of dom nodes?

### ISSUE THREAD

**Issue by maz-1** [gomita/firegestures#97]
Someone made a modified version to use html5 canvas to draw the track , see here : http://pan.baidu.com/s/1ntlxf9R
It provides better perfomance and appearance.It would be good if the modification can be merged into the official one.

**Comment by gomita** [comment]
It seems great.
This is an experimental version using html5 canvas:
http://www.xuldev.org/firegestures/firegestures-1.10a1.xpi
Should I ask the author for the license?

**Comment by maz-1** [comment]
The modder is OK with that.
http://tieba.baidu.com/p/3765992195

**Comment by gomita** [comment]
@maz-1 
Thank you for confirming to the author.
